source:
  host: imap.source-server.com
  user: your_source_username
  pass: your_source_password
  port: 993
  ssl: true

destination:
  host: imap.destination-server.com
  user: your_destination_username
  pass: your_destination_password
  port: 993
  ssl: true

database:
  path: migrate_resume.sqlite  # Local SQLite database to track migrated UIDs

# Optional advanced tuning
batch_size: 50          # Number of emails per fetch/append batch
sleep_between: 2        # Seconds to sleep between batches
